// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: account.srv.proto

package dto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_AccountType_UnUsed  AccountType = 0 // 未使用
	AccountType_AccountType_Used    AccountType = 1 // 已使用
	AccountType_AccountType_Manager AccountType = 2 // 管理员
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "AccountType_UnUsed",
		1: "AccountType_Used",
		2: "AccountType_Manager",
	}
	AccountType_value = map[string]int32{
		"AccountType_UnUsed":  0,
		"AccountType_Used":    1,
		"AccountType_Manager": 2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_srv_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_account_srv_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_account_srv_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_account_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_account_srv_proto_rawDescGZIP(), []int{0}
}

type AccountGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string      `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`                              // 币种
	Remarks  string      `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`                                // 备注
	Type     AccountType `protobuf:"varint,3,opt,name=type,proto3,enum=Account.service.v1.AccountType" json:"type,omitempty"` // 类别
}

func (x *AccountGetReq) Reset() {
	*x = AccountGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountGetReq) ProtoMessage() {}

func (x *AccountGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountGetReq.ProtoReflect.Descriptor instead.
func (*AccountGetReq) Descriptor() ([]byte, []int) {
	return file_account_srv_proto_rawDescGZIP(), []int{1}
}

func (x *AccountGetReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountGetReq) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *AccountGetReq) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_AccountType_UnUsed
}

type AccountGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 币种
}

func (x *AccountGetResp) Reset() {
	*x = AccountGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountGetResp) ProtoMessage() {}

func (x *AccountGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountGetResp.ProtoReflect.Descriptor instead.
func (*AccountGetResp) Descriptor() ([]byte, []int) {
	return file_account_srv_proto_rawDescGZIP(), []int{2}
}

func (x *AccountGetResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_account_srv_proto protoreflect.FileDescriptor

var file_account_srv_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x7a, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2a, 0x0a, 0x0e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2a, 0x54, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x55, 0x73, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55,
	0x73, 0x65, 0x64, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x10, 0x02, 0x32, 0xa1,
	0x01, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x72, 0x76, 0x12, 0x3c, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x19, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x55, 0x0a, 0x0a, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x64, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_srv_proto_rawDescOnce sync.Once
	file_account_srv_proto_rawDescData = file_account_srv_proto_rawDesc
)

func file_account_srv_proto_rawDescGZIP() []byte {
	file_account_srv_proto_rawDescOnce.Do(func() {
		file_account_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_srv_proto_rawDescData)
	})
	return file_account_srv_proto_rawDescData
}

var file_account_srv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_srv_proto_goTypes = []interface{}{
	(AccountType)(0),       // 0: Account.service.v1.AccountType
	(*Empty)(nil),          // 1: Account.service.v1.Empty
	(*AccountGetReq)(nil),  // 2: Account.service.v1.AccountGetReq
	(*AccountGetResp)(nil), // 3: Account.service.v1.AccountGetResp
}
var file_account_srv_proto_depIdxs = []int32{
	0, // 0: Account.service.v1.AccountGetReq.type:type_name -> Account.service.v1.AccountType
	1, // 1: Account.service.v1.AccountSrv.Ping:input_type -> Account.service.v1.Empty
	2, // 2: Account.service.v1.AccountSrv.AccountGet:input_type -> Account.service.v1.AccountGetReq
	1, // 3: Account.service.v1.AccountSrv.Ping:output_type -> Account.service.v1.Empty
	3, // 4: Account.service.v1.AccountSrv.AccountGet:output_type -> Account.service.v1.AccountGetResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_srv_proto_init() }
func file_account_srv_proto_init() {
	if File_account_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_srv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_srv_proto_goTypes,
		DependencyIndexes: file_account_srv_proto_depIdxs,
		EnumInfos:         file_account_srv_proto_enumTypes,
		MessageInfos:      file_account_srv_proto_msgTypes,
	}.Build()
	File_account_srv_proto = out.File
	file_account_srv_proto_rawDesc = nil
	file_account_srv_proto_goTypes = nil
	file_account_srv_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountSrvClient is the client API for AccountSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountSrvClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// 获取帐号
	AccountGet(ctx context.Context, in *AccountGetReq, opts ...grpc.CallOption) (*AccountGetResp, error)
}

type accountSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountSrvClient(cc grpc.ClientConnInterface) AccountSrvClient {
	return &accountSrvClient{cc}
}

func (c *accountSrvClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Account.service.v1.AccountSrv/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountSrvClient) AccountGet(ctx context.Context, in *AccountGetReq, opts ...grpc.CallOption) (*AccountGetResp, error) {
	out := new(AccountGetResp)
	err := c.cc.Invoke(ctx, "/Account.service.v1.AccountSrv/AccountGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountSrvServer is the server API for AccountSrv service.
type AccountSrvServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	// 获取帐号
	AccountGet(context.Context, *AccountGetReq) (*AccountGetResp, error)
}

// UnimplementedAccountSrvServer can be embedded to have forward compatible implementations.
type UnimplementedAccountSrvServer struct {
}

func (*UnimplementedAccountSrvServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAccountSrvServer) AccountGet(context.Context, *AccountGetReq) (*AccountGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountGet not implemented")
}

func RegisterAccountSrvServer(s *grpc.Server, srv AccountSrvServer) {
	s.RegisterService(&_AccountSrv_serviceDesc, srv)
}

func _AccountSrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountSrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account.service.v1.AccountSrv/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountSrvServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountSrv_AccountGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountSrvServer).AccountGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account.service.v1.AccountSrv/AccountGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountSrvServer).AccountGet(ctx, req.(*AccountGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Account.service.v1.AccountSrv",
	HandlerType: (*AccountSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AccountSrv_Ping_Handler,
		},
		{
			MethodName: "AccountGet",
			Handler:    _AccountSrv_AccountGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.srv.proto",
}
