// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Currency int32

const (
	Currency_ETH Currency = 0
)

var Currency_name = map[int32]string{
	0: "ETH",
}
var Currency_value = map[string]int32{
	"ETH": 0,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}
func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_currency_396b0a315933e015, []int{0}
}

func init() {
	proto.RegisterEnum("common.Currency", Currency_name, Currency_value)
}

func init() { proto.RegisterFile("currency.proto", fileDescriptor_currency_396b0a315933e015) }

var fileDescriptor_currency_396b0a315933e015 = []byte{
	// 69 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2e, 0x2d, 0x2a,
	0x4a, 0xcd, 0x4b, 0xae, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x12, 0xe6, 0xe2, 0x70, 0x86, 0xca, 0x08, 0xb1, 0x73, 0x31, 0xbb, 0x86, 0x78,
	0x08, 0x30, 0x24, 0xb1, 0x81, 0xd5, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xe6, 0xd8,
	0x91, 0x35, 0x00, 0x00, 0x00,
}
