// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Net int32

const (
	Net_ETH_Miner Net = 0
)

var Net_name = map[int32]string{
	0: "ETH_Miner",
}
var Net_value = map[string]int32{
	"ETH_Miner": 0,
}

func (x Net) String() string {
	return proto.EnumName(Net_name, int32(x))
}
func (Net) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_net_7a2e654b98fb00c1, []int{0}
}

func init() {
	proto.RegisterEnum("common.Net", Net_name, Net_value)
}

func init() { proto.RegisterFile("net.proto", fileDescriptor_net_7a2e654b98fb00c1) }

var fileDescriptor_net_7a2e654b98fb00c1 = []byte{
	// 70 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4b, 0x2d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x12, 0xe1,
	0x62, 0xf6, 0x4b, 0x2d, 0x11, 0xe2, 0xe5, 0xe2, 0x74, 0x0d, 0xf1, 0x88, 0xf7, 0xcd, 0xcc, 0x4b,
	0x2d, 0x12, 0x60, 0x48, 0x62, 0x03, 0x2b, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xb8,
	0x6d, 0xa6, 0x31, 0x00, 0x00, 0x00,
}
