version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-server
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db   # /data/db是container中存放数据位置
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: wallet
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    #restart: always

  adminer:
    image: adminer
    container_name: adminer-server
    #restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    container_name: redis-server
    #restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/db/:/data/